ALTER TABLE `USERMASSIVEANALISYS` DROP FOREIGN KEY `FK_USERMASSIVEANALISYS_VAR_INVOLVED_FIRST_ID`
ALTER TABLE `USERMASSIVEANALISYS` DROP FOREIGN KEY `FK_USERMASSIVEANALISYS_VAR_INVOLVED_SECOND_ID`
ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `USERHISTORY_USERMASSIVEANALISYS_ibfk_1`
ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `USERHISTORY_USERMASSIVEANALISYS_ibfk_2`
ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `SRHISTORYUSERMASSIVEANALISYSlcalresearchanalisysID`
ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `SRHSTRYUSERMASSIVEANALISYSRgstrdUserAnalysisRootID`

ALTER TABLE `USERHISTORY_USERMASSIVESETTING` DROP FOREIGN KEY `USERHISTORY_USERMASSIVESETTING_ibfk_1`
ALTER TABLE `USERHISTORY_USERMASSIVESETTING` DROP FOREIGN KEY `USERHISTORY_USERMASSIVESETTING_ibfk_2`
ALTER TABLE `USERHISTORY_USERMASSIVESETTING` DROP FOREIGN KEY `SERHISTORYUSERMASSIVESETTINGlcalresearchsettingsID`
ALTER TABLE `USERHISTORY_USERMASSIVESETTING` DROP FOREIGN KEY `SERHISTORYUSERMASSIVESETTINGRgisteredUserHistoryID`

ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `USERHISTORY_USERMASSIVEANALISYS_ibfk_1`, ADD FOREIGN KEY (`RegisteredUserAnalysisRoot_ID`) REFERENCES `databankkiis`.`USERHISTORY`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `USERHISTORY_USERMASSIVEANALISYS` DROP FOREIGN KEY `USERHISTORY_USERMASSIVEANALISYS_ibfk_2`, ADD FOREIGN KEY (`local_research_analisys_ID`) REFERENCES `databankkiis`.`USERMASSIVEANALISYS`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

