ALTER TABLE  `USERMASSIVEANALISYS` DROP FOREIGN KEY  `USERMASSIVEANALISYS_ibfk_24`
ALTER TABLE  `USERMASSIVEANALISYS` DROP FOREIGN KEY  `USERMASSIVEANALISYS_ibfk_25`
ALTER TABLE  `USERMASSIVEANALISYS` DROP FOREIGN KEY  `USERMASSIVEANALISYS_ibfk_26`


